"""Sample a small, category-balanced subset from a source-only edit manifest and
emit the two files the feasibility run needs:

  1. <out_dir>/bernini_tasks.json -- batch input for the OFFLINE Bernini teacher
     (my_project/Bernini/infer_multi_gpu.py --inputs ...). Each task carries the
     absolute source `video` and the target `output` mp4 path to be generated.
  2. <out_dir>/cf_manifest.json   -- input for gen_edit_targets.py (causal_forcing
     env): {prompt, task_type, source, target, refs} with absolute paths, so the
     SAME (source, teacher-target) pair gets VAE-encoded into training latents.

The source manifest is the ReCo extraction (source-only); category is inferred
from the source path (/add/, /remove/, /replace/).

Run (any python):
    python bernini_causvid/tools/build_subset_manifest.py \
        --manifest /apdcephfs/.../distill_for_bernini/edit_manifest.json \
        --out_dir  /apdcephfs/.../distill_for_bernini/feasibility_v1 \
        --per_cat 16 --guidance_mode v2v_apg --seed 0
"""
import argparse
import json
import os
import random

CATS = ("add", "remove", "replace")


def categorize(src_path: str) -> str:
    for c in CATS:
        if f"/{c}/" in src_path:
            return c
    return "other"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--manifest", required=True, help="source-only edit_manifest.json")
    ap.add_argument("--out_dir", required=True)
    ap.add_argument("--per_cat", type=int, default=16, help="samples per category")
    ap.add_argument("--guidance_mode", default="v2v_apg", help="Bernini v2v guidance mode")
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--target_from_manifest", action="store_true",
                    help="use the `target` already present in the source manifest "
                         "(ReCo GT route); skip emitting bernini_tasks.json")
    args = ap.parse_args()

    os.makedirs(os.path.join(args.out_dir, "targets"), exist_ok=True)
    items = json.load(open(args.manifest))

    buckets = {c: [] for c in CATS}
    for it in items:
        c = categorize(it["source"])
        if c in buckets:
            buckets[c].append(it)

    rng = random.Random(args.seed)
    chosen = []
    for c in CATS:
        pool = buckets[c]
        rng.shuffle(pool)
        take = pool[: args.per_cat]
        if len(take) < args.per_cat:
            print(f"[warn] category '{c}' only has {len(take)} (< {args.per_cat})")
        for it in take:
            it = dict(it)
            it["_cat"] = c
            chosen.append(it)
    rng.shuffle(chosen)

    bernini_tasks, cf_manifest = [], []
    for i, it in enumerate(chosen):
        prompt = it["prompt"]
        src = os.path.abspath(it["source"])
        refs = [os.path.abspath(r) for r in it.get("refs", [])]
        if args.target_from_manifest:
            # ReCo GT route: target is the dataset's own edited video.
            tgt = os.path.abspath(it["target"])
        else:
            # Bernini route: target is an mp4 to be generated by the offline teacher.
            tgt = os.path.abspath(os.path.join(args.out_dir, "targets", f"{i:05d}_{it['_cat']}.mp4"))
            bernini_tasks.append({
                "task_type": "v2v",
                "guidance_mode": args.guidance_mode,
                "prompt": prompt,
                "video": src,
                "output": tgt,
            })
        cf_manifest.append({
            "prompt": prompt,
            "task_type": "v2v",
            "source": src,
            "refs": refs,
            "target": tgt,
        })

    cf = os.path.join(args.out_dir, "cf_manifest.json")
    json.dump(cf_manifest, open(cf, "w"), ensure_ascii=False, indent=2)
    if not args.target_from_manifest:
        bt = os.path.join(args.out_dir, "bernini_tasks.json")
        json.dump(bernini_tasks, open(bt, "w"), ensure_ascii=False, indent=2)
        print(f"[subset] wrote {bt}")

    meta = {
        "source_manifest": os.path.abspath(args.manifest),
        "out_dir": os.path.abspath(args.out_dir),
        "per_cat": args.per_cat, "guidance_mode": args.guidance_mode,
        "seed": args.seed, "total": len(chosen),
        "target_source": "manifest_gt" if args.target_from_manifest else "bernini_teacher",
        "by_cat": {c: sum(1 for x in chosen if x["_cat"] == c) for c in CATS},
    }
    json.dump(meta, open(os.path.join(args.out_dir, "subset_meta.json"), "w"), indent=2)
    print(f"[subset] total={len(chosen)} by_cat={meta['by_cat']} target={meta['target_source']}")
    print(f"[subset] wrote {cf}")


if __name__ == "__main__":
    main()
