model_name: Bernini-R-1.3B
model_path: /apdcephfs_hzlf/share_1227201/xinyu/Causal-Forcing/wan_models/Bernini-R-1.3B
text_encoder_path: /apdcephfs_hzlf/share_1227201/xinyu/Causal-Forcing/wan_models/Wan2.1-T2V-1.3B/models_t5_umt5-xxl-enc-bf16.pth
tokenizer_path: /apdcephfs_hzlf/share_1227201/xinyu/Causal-Forcing/wan_models/Wan2.1-T2V-1.3B/google/umt5-xxl
vae_path: /apdcephfs_hzlf/share_1227201/xinyu/Causal-Forcing/wan_models/Wan2.1-T2V-1.3B/Wan2.1_VAE.pth
causal: true
num_frame_per_block: 3
timestep_shift: 5.0
guidance_mode: v2v_apg
guidance_scale: 3.0
omega_v: 1.25
omega_i: 4.5
omega_ti: 4.0
apg_eta: 0.5
apg_norm_threshold: 50.0
generator_ckpt: runs/bernini_edit_ar/20260702_133519/checkpoints/checkpoint_model_002500/model.pt
fake_score_init: teacher
allow_raw_bernini_init: false
source_timestep_mode: target
source_noise: 0
context_noise: 0
score_source_timestep_mode: target
score_causal_source: false
distribution_loss: dmd
denoising_loss_type: flow
denoising_step_list:
- 1000
- 750
- 500
- 250
warp_denoising_step: true
ts_schedule: false
min_score_timestep: 0
num_train_timestep: 1000
generator_start_step: 0
dfake_gen_update_ratio: 5
image_or_video_shape:
- 1
- 21
- 16
- 60
- 104
mixed_precision: true
gradient_checkpointing: true
batch_size: 1
gradient_accumulation_steps: 1
lr: 2.0e-06
lr_critic: 4.0e-07
beta1: 0.0
beta2: 0.999
beta1_critic: 0.0
beta2_critic: 0.999
weight_decay: 0.0
ema_weight: 0.99
ema_start_step: 1
seed: 0
sharding_strategy: hybrid_full
data_path: data/edit_smoke/index.json
negative_prompt: 色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走
