model_name: Bernini-R-1.3B
model_path: /opt/dlami/nvme/chenxinyu/project/Causal-Forcing/wan_models/Bernini-R-1.3B-Wan
text_encoder_path: /opt/dlami/nvme/chenxinyu/project/Causal-Forcing/wan_models/Wan2.1-T2V-1.3B/models_t5_umt5-xxl-enc-bf16.pth
tokenizer_path: /opt/dlami/nvme/chenxinyu/project/Causal-Forcing/wan_models/Wan2.1-T2V-1.3B/google/umt5-xxl
vae_path: /opt/dlami/nvme/chenxinyu/project/Causal-Forcing/wan_models/Wan2.1-T2V-1.3B/Wan2.1_VAE.pth
causal: true
num_frame_per_block: 3
timestep_shift: 5.0
cache_text_embeds: true
teacher_forcing: true
source_timestep_mode: source
ref_timestep: 0
discrete_cd_N: 48
guidance_scale: 3.0
guidance_mode_by_task_type:
  t2v: t2v
  s2v: v2v_apg
  v2v: v2v_apg
  i2i: v2v_apg
  rv2v: rv2v_apg
apg_eta: 0.5
apg_norm_thresholds:
- 50.0
- 50.0
- 50.0
omega_v: 1.25
omega_i: 4.5
omega_ti: 4.0
num_train_timestep: 1000
generator_ckpt: /opt/dlami/nvme/chenxinyu/project/Universal-Edit-Forcing/runs/universal_edit_ar/20260818_024208/checkpoints/checkpoint_model_007000/model.pt
image_or_video_shape:
- 1
- 21
- 16
- 60
- 104
mixed_precision: true
gradient_checkpointing: true
batch_size: 1
gradient_accumulation_steps: 1
lr: 5.0e-07
beta1: 0.0
beta2: 0.999
weight_decay: 0.0
ema_weight: 0.99
ema_start_step: 0
seed: 0
sharding_strategy: grad_op
data_path: /opt/dlami/nvme/chenxinyu/data/Universal-Edit-Metadata/mixed_train/index_image_t2v_video_all.json
negative_prompt: 色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走
dataset_sampling_weights:
  add_delete_sub_good_only: 0.0
  fitvto_100k: 0.0
  openve_3m_60k: 0.0
  openvid_t2v: 0.4
  pico_banana_400k_single_sft_100k: 0.0
  reco: 0.5
  tripvvt: 0.1
  uniredit_data_100k: 0.0
dataset_max_lat_frames:
  openvid_t2v: 21
  tripvvt: 21
eval_samples:
- name: t2v_openvid
  dataset: openvid_t2v
  task_type: t2v
- name: v2v_reco_add
  dataset: reco
  task_type: v2v
  edit_type: add
- name: rv2v_tripvvt
  dataset: tripvvt
  task_type: rv2v
